#! /usr/bin/env bash

set -e

if ! command -v brew >/dev/null; then
  echo "==> Installing Homebrew ..."
  if [[ "$OSTYPE" = darwin* ]]; then
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  else
    curl -fsSL 'https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh' | sh -c
  fi
fi

echo "==> Install Homebrew dependencies"
# brew bundle

update_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  echo "==> Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    echo "==> Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      echo "==> Updating shell to ZSH"
      update_shell
    fi
    ;;
  *)
    echo "==> Updating shell to ZSH"
    update_shell
    ;;
esac

Oh My ZSH
echo "==> Installing oh my zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- p10k
echo "==> Installing p10k"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.dotfiles/oh-my-zsh/custom}/themes/powerlevel10k

ln -s $HOME/Library/Application Support/Code/User/settings.json ~/.vscode-settings

echo "==> Installing Node, Yarn, Ruby"
asdf plugin-add nodejs
asdf plugin-add yarn
asdf plugin-add ruby

bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

asdf install nodejs 12.20
asdf install yarn 1.22.10
asdf install ruby 2.5.8

source ./rcup
